/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'tertiary-fixed-dim': '#d2bbff',
        'on-secondary-container': '#fefcff',
        'on-primary-fixed': '#001453',
        'inverse-surface': '#213145',
        'surface-tint': '#3755c3',
        primary: '#00288e',
        'on-surface': '#0b1c30',
        'on-tertiary-fixed-variant': '#5a00c6',
        'on-primary-container': '#a8b8ff',
        background: '#f8f9ff',
        'tertiary-fixed': '#eaddff',
        'on-tertiary': '#ffffff',
        secondary: '#0051d5',
        'surface-container': '#e5eeff',
        'on-error': '#ffffff',
        surface: '#f8f9ff',
        'on-background': '#0b1c30',
        'on-secondary': '#ffffff',
        'secondary-container': '#316bf3',
        'surface-container-highest': '#d3e4fe',
        'primary-fixed-dim': '#b8c4ff',
        'on-primary-fixed-variant': '#173bab',
        'inverse-on-surface': '#eaf1ff',
        'on-secondary-fixed-variant': '#003ea8',
        'outline-variant': '#c4c5d5',
        'surface-variant': '#d3e4fe',
        'on-secondary-fixed': '#00174b',
        outline: '#757684',
        'tertiary-container': '#5f00d1',
        'surface-container-high': '#dce9ff',
        'surface-bright': '#f8f9ff',
        'error-container': '#ffdad6',
        'primary-container': '#1e40af',
        'primary-fixed': '#dde1ff',
        'surface-container-low': '#eff4ff',
        'on-tertiary-fixed': '#25005a',
        tertiary: '#440098',
        'secondary-fixed-dim': '#b4c5ff',
        'on-tertiary-container': '#c9aeff',
        'inverse-primary': '#b8c4ff',
        'on-error-container': '#93000a',
        'on-surface-variant': '#444653',
        error: '#ba1a1a',
        'surface-dim': '#cbdbf5',
        'secondary-fixed': '#dbe1ff',
        'on-primary': '#ffffff',
        'surface-container-lowest': '#ffffff',
      },
      fontFamily: { sans: ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'] },
      boxShadow: { xs: '0 1px 2px 0 rgb(0 0 0 / 0.05)' },
    },
  },
  plugins: [],
}
